server:
  error:
    include-exception: true
    include-stacktrace: always


logging:
  level:
    root: info
    com.musinsa: debug
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console